export { default as Header } from '~/components/layout/header'
export { default as Footer } from '~/components/layout/footer'
export { default as Hero } from '~/components/section/hero'
export { default as Services } from '~/components/section/services'
export { default as Testimonials } from '~/components/section/testimonials'
export { default as ImageBanner } from '~/components/section/image-banner'
